version: '3'
services:
  nextjs-blog-enviroment:
    container_name: nextjs-blog-enviroment
    image: node:20-alpine
    tty: true
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"